language: ruby
rvm:
- 2.2.5
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  ssh_known_hosts: samarashuttle.cr
script:
- bash _script/build.sh
after_success:
- bash _script/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_6a97e7e82599_key -iv $encrypted_6a97e7e82599_iv
  -in travis_deploy.enc -out travis_deploy -d
- bash _script/install.sh
