language: ruby
rvm:
- 2.2.5

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  ssh_known_hosts: samarashuttle.cr
before_install:
  - bash _script/install.sh
script:
  - bash _script/build.sh
#  - bash _script/test.sh
after_success:
  - bash _script/deploy.sh


## OLD

#before_script:
# - chmod +x ./_script/cibuild # or do this locally and commit
# - chmod +x ./_script/deploy.sh # or do this locally and commit


# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
#script: ./_script/deploy.sh

# branch whitelist, only for GitHub Pages
#branches:
#  only:
#  - gh-pages     # test the gh-pages branch

#env:
#  global:
#  - ENCRYPTION_LABEL: "6a97e7e82599"
#  - COMMIT_AUTHOR_EMAIL: "travis_deploy@samarashuttle.cr"
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

#sudo: false # route your build to the container-based infrastructure for a faster build
#deploy:
#  provider: script
#  script: _script/deploy.sh
#  on:
#    branch: gh-pages
